name: workflow
# label used for menu selection
label: Simple Workflow

description: |
  This skillet demonstrates a simple workflow.
type: workflow

# Labels allow grouping and type specific options and are generally only used in advanced cases
labels:
  collection:
    - ezhi-myCollection

# variables define the things an operator may customize in this skillet. Things like DNS servers, NTP addresses, etc
# may be customized for each deployment. Each variable will be rendered as a form field in the panhandler application
variables:


# Snippets is an ordered list of configuration xml fragments that will be pushed to the PAN-OS NGFW. The xpath
# determines where in the configuration hierarchy the xml fragment will be set. 'file' indicates the name of the file
# to load and parse. Jinja2 style variables will be variable interpolated using the values of the 'variables' defined
# in the 'variables' section.
snippets:
  - name: get-api-key
  - name: get-system-info
  - name: captured_values_example