# skillet preamble information used by panhandler
# ---------------------------------------------------------------------
# unique snippet name
name: Step2-ARP-Retriever
# label used for menu selection
label: Step2-ARP-Retriever
description: Retrieve ARP entries from PAN-OS

# type of device configuration
# common types are panorama, panos, and template
# https://github.com/PaloAltoNetworks/panhandler/blob/develop/docs/metadata_configuration.rst
type: rest
# preload static or default-based templates
extends:

# grouping of like snippets for dynamic menu creation in panhandler
labels:
  collection:
    - ezhi-myCollection

# ---------------------------------------------------------------------
# end of preamble section

# variables section
# ---------------------------------------------------------------------
# variables used in the configuration templates
# type_hint defines the form field used by panhandler
# type_hints can be text, ip_address, or dropdown
variables:
  - name: host_ip
    description: Firewall host ip address
    default: 192.168.55.10
    type_hint: text
  - name: api_key
    description: firewall api_key
    default: 0000-0000-0000-0000-0000
    type_hint: text
  - name: interface
    description: interface dropdown list
    default: all
    type_hint: dropdown
    dd_list:
      - key: all
        value: all
      - key: ethernet1/1
        value: ethernet1/1
      - key: ethernet1/2
        value: ethernet1/2
      - key: ethernet1/3
        value: ethernet1/3
      - key: ethernet1/4
        value: ethernet1/4
      - key: ethernet1/5
        value: ethernet1/5
      - key: ethernet1/6
        value: ethernet1/6
      - key: ethernet1/7
        value: ethernet1/7
      - key: ethernet1/8
        value: ethernet1/8
# ---------------------------------------------------------------------
# end of variables section

# snippets section
# ---------------------------------------------------------------------
# snippets used for api configuration including xpath and element as file name
# files will load in the order listed
snippets:
  - name: track
    path: https://{{ host_ip }}/api/?type=op&cmd=<show><arp><entry name='{{ interface }}'/></arp></show>&key={{ api_key }}
    operation: get
# ---------------------------------------------------------------------
# end of snippets section